import phone from "@/assets/product-phone.jpg";
import headphones from "@/assets/product-headphones.jpg";
import laptop from "@/assets/product-laptop.jpg";
import watch from "@/assets/product-watch.jpg";
import sneaker from "@/assets/product-sneaker.jpg";
import type { Negotiation, Product, Seller } from "@/types/marketplace";

const techstore: Seller = {
  id: "s_techstore",
  name: "TechStore",
  verified: true,
  rating: 4.9,
  sales: 1284,
  responseTime: "Under 20 minutes",
  memberSince: "2021",
};

const soundhaus: Seller = {
  id: "s_soundhaus",
  name: "SoundHaus",
  verified: true,
  rating: 4.7,
  sales: 612,
  responseTime: "Under 1 hour",
  memberSince: "2022",
};

const atelier: Seller = {
  id: "s_atelier",
  name: "Atelier Lagos",
  verified: false,
  rating: 4.4,
  sales: 173,
  responseTime: "Around 3 hours",
  memberSince: "2024",
};

export const products: Product[] = [
  {
    id: "iphone-15-pro",
    slug: "iphone-15-pro",
    name: "iPhone 15 Pro",
    category: "Phones",
    price: 1250000,
    currency: "NGN",
    image: phone,
    rating: 4.8,
    reviewCount: 124,
    negotiable: true,
    inStock: 7,
    condition: "Brand new, sealed",
    location: "Lagos, Nigeria",
    description:
      "The iPhone 15 Pro pairs a titanium frame with the A17 Pro chip for flagship performance in a lighter body. Sold sealed with full manufacturer warranty, verified IMEI and a 7-day return window through marketplace escrow.",
    highlights: [
      "Sealed unit with 12-month warranty",
      "Escrow-protected payment",
      "Ships within 24 hours in Lagos",
    ],
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR, 120Hz" },
      { label: "Chip", value: "A17 Pro, 6-core GPU" },
      { label: "Storage", value: "256GB" },
      { label: "Camera", value: "48MP main + 12MP ultra wide" },
      { label: "Battery", value: "Up to 23 hours video" },
      { label: "Build", value: "Grade 5 titanium" },
      { label: "Colour", value: "Natural Titanium" },
      { label: "Warranty", value: "12 months, seller-backed" },
    ],
    seller: techstore,
    reviews: [
      {
        id: "r1",
        author: "Adaeze O.",
        rating: 5,
        createdAt: "2 weeks ago",
        body: "Arrived sealed the next morning. Negotiated ₦80,000 off through the chat, which felt surprisingly civil.",
      },
      {
        id: "r2",
        author: "Kunle A.",
        rating: 5,
        createdAt: "1 month ago",
        body: "Seller responded in minutes and the AI suggestion helped me land a fair price without going back and forth for days.",
      },
      {
        id: "r3",
        author: "Mercy I.",
        rating: 4,
        createdAt: "1 month ago",
        body: "Great device and packaging. Delivery took a day longer than promised but communication was clear.",
      },
    ],
  },
  {
    id: "studio-headphones",
    slug: "studio-headphones",
    name: "Aurora Studio Headphones",
    category: "Audio",
    price: 320000,
    currency: "NGN",
    image: headphones,
    rating: 4.6,
    reviewCount: 58,
    negotiable: true,
    inStock: 12,
    condition: "Brand new",
    location: "Abuja, Nigeria",
    description:
      "Reference-grade closed-back headphones with adaptive noise cancellation and 40-hour battery life.",
    highlights: ["Adaptive ANC", "40-hour battery", "Hard travel case included"],
    specs: [
      { label: "Drivers", value: "40mm dynamic" },
      { label: "Battery", value: "40 hours ANC on" },
      { label: "Codecs", value: "LDAC, AAC, SBC" },
      { label: "Weight", value: "268g" },
    ],
    seller: soundhaus,
    reviews: [
      {
        id: "r1",
        author: "Tomi B.",
        rating: 5,
        createdAt: "3 weeks ago",
        body: "Sound stage is excellent for the price and the seller accepted my first offer.",
      },
    ],
  },
  {
    id: "macbook-air-m3",
    slug: "macbook-air-m3",
    name: "MacBook Air M3 13\"",
    category: "Laptops",
    price: 1780000,
    currency: "NGN",
    image: laptop,
    rating: 4.9,
    reviewCount: 91,
    negotiable: true,
    inStock: 3,
    condition: "Brand new, sealed",
    location: "Lagos, Nigeria",
    description: "Fanless, 18-hour battery laptop with the M3 chip, 16GB unified memory and 512GB SSD.",
    highlights: ["16GB / 512GB", "18-hour battery", "Escrow-protected payment"],
    specs: [
      { label: "Chip", value: "Apple M3, 8-core CPU" },
      { label: "Memory", value: "16GB unified" },
      { label: "Storage", value: "512GB SSD" },
      { label: "Display", value: "13.6\" Liquid Retina" },
    ],
    seller: techstore,
    reviews: [],
  },
  {
    id: "smartwatch-series-9",
    slug: "smartwatch-series-9",
    name: "Pulse Watch Series 9",
    category: "Wearables",
    price: 480000,
    currency: "NGN",
    image: watch,
    rating: 4.5,
    reviewCount: 37,
    negotiable: false,
    inStock: 20,
    condition: "Brand new",
    location: "Port Harcourt, Nigeria",
    description: "Fitness-first smartwatch with ECG, always-on display and a woven titanium loop.",
    highlights: ["ECG + SpO2", "Always-on display", "Titanium loop"],
    specs: [
      { label: "Case", value: "45mm titanium" },
      { label: "Battery", value: "36 hours" },
      { label: "Water rating", value: "50m" },
      { label: "Sensors", value: "ECG, SpO2, temperature" },
    ],
    seller: soundhaus,
    reviews: [],
  },
  {
    id: "leather-sneakers",
    slug: "leather-sneakers",
    name: "Hand-stitched Leather Sneakers",
    category: "Fashion",
    price: 145000,
    currency: "NGN",
    image: sneaker,
    rating: 4.3,
    reviewCount: 22,
    negotiable: true,
    inStock: 5,
    condition: "Made to order",
    location: "Lagos, Nigeria",
    description: "Full-grain leather sneakers stitched to order by a Lagos atelier. Sizes 39-46.",
    highlights: ["Full-grain leather", "Made to order", "Free resole once"],
    specs: [
      { label: "Upper", value: "Full-grain leather" },
      { label: "Sole", value: "Stitched rubber" },
      { label: "Lead time", value: "7-10 days" },
      { label: "Sizes", value: "39 - 46" },
    ],
    seller: atelier,
    reviews: [],
  },
  {
    id: "iphone-15-pro-max",
    slug: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    category: "Phones",
    price: 1620000,
    currency: "NGN",
    image: phone,
    rating: 4.7,
    reviewCount: 64,
    negotiable: true,
    inStock: 4,
    condition: "Brand new, sealed",
    location: "Lagos, Nigeria",
    description: "The larger Pro Max with a 5x tetraprism telephoto camera and all-day battery.",
    highlights: ["5x telephoto", "1TB option", "Sealed unit"],
    specs: [
      { label: "Display", value: "6.7\" Super Retina XDR" },
      { label: "Chip", value: "A17 Pro" },
      { label: "Storage", value: "512GB" },
      { label: "Camera", value: "48MP + 5x telephoto" },
    ],
    seller: techstore,
    reviews: [],
  },
];

export const categories = [
  { id: "phones", label: "Phones", count: 1840 },
  { id: "laptops", label: "Laptops", count: 962 },
  { id: "audio", label: "Audio", count: 731 },
  { id: "wearables", label: "Wearables", count: 418 },
  { id: "fashion", label: "Fashion", count: 2210 },
  { id: "home", label: "Home", count: 1104 },
];

export function buildInitialNegotiation(product: Product): Negotiation {
  return {
    id: `neg_${product.id}`,
    productId: product.id,
    status: "negotiating",
    currentOffer: null,
    messages: [
      {
        id: "m1",
        author: "seller",
        body: `Hi! Thanks for your interest in the ${product.name}. It's in stock and ready to ship today.`,
        createdAt: "10:02",
      },
      {
        id: "m2",
        author: "buyer",
        body: "Is the price flexible if I pay today?",
        createdAt: "10:04",
      },
      {
        id: "m3",
        author: "seller",
        body: `The lowest I can do is ${new Intl.NumberFormat("en-NG", { style: "currency", currency: product.currency, maximumFractionDigits: 0 }).format(Math.round(product.price * 0.96))}.`,
        createdAt: "10:06",
      },
      {
        id: "m4",
        author: "ai",
        body: "Based on the seller's counteroffer and recent sales of this item, a next offer around the figure below is likely to be accepted.",
        createdAt: "10:06",
        suggestion: {
          amount: Math.round((product.price * 0.92) / 1000) * 1000,
          message: "Would you consider {amount}? I can pay immediately through escrow.",
        },
      },
    ],
  };
}