/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NegotiationsNegotiationIdRouteImport } from './routes/negotiations.$negotiationId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as ApiBackendSplatRouteImport } from './routes/api/backend/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NegotiationsNegotiationIdRoute =
  NegotiationsNegotiationIdRouteImport.update({
    id: '/negotiations/$negotiationId',
    path: '/negotiations/$negotiationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackendSplatRoute = ApiBackendSplatRouteImport.update({
  id: '/api/backend/$',
  path: '/api/backend/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/negotiations/$negotiationId': typeof NegotiationsNegotiationIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/negotiations/$negotiationId': typeof NegotiationsNegotiationIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/dashboard': typeof DashboardRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/negotiations/$negotiationId': typeof NegotiationsNegotiationIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/api/backend/$': typeof ApiBackendSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/sell'
    | '/seller'
    | '/signin'
    | '/signup'
    | '/negotiations/$negotiationId'
    | '/orders/$orderId'
    | '/product/$productId'
    | '/api/backend/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/sell'
    | '/seller'
    | '/signin'
    | '/signup'
    | '/negotiations/$negotiationId'
    | '/orders/$orderId'
    | '/product/$productId'
    | '/api/backend/$'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/dashboard'
    | '/sell'
    | '/seller'
    | '/signin'
    | '/signup'
    | '/negotiations/$negotiationId'
    | '/orders/$orderId'
    | '/product/$productId'
    | '/api/backend/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  DashboardRoute: typeof DashboardRoute
  SellRoute: typeof SellRoute
  SellerRoute: typeof SellerRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  NegotiationsNegotiationIdRoute: typeof NegotiationsNegotiationIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ApiBackendSplatRoute: typeof ApiBackendSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiations/$negotiationId': {
      id: '/negotiations/$negotiationId'
      path: '/negotiations/$negotiationId'
      fullPath: '/negotiations/$negotiationId'
      preLoaderRoute: typeof NegotiationsNegotiationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backend/$': {
      id: '/api/backend/$'
      path: '/api/backend/$'
      fullPath: '/api/backend/$'
      preLoaderRoute: typeof ApiBackendSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  DashboardRoute: DashboardRoute,
  SellRoute: SellRoute,
  SellerRoute: SellerRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  NegotiationsNegotiationIdRoute: NegotiationsNegotiationIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ApiBackendSplatRoute: ApiBackendSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
